print("=========================================")
print("Programmer: Daniel Dupra")
print("Date Created: July 06, 2023")
print("Description of the program: It is about the Progrmmer's biodata")
print("\n")
print("First Name: Daniel")
print("Middle Name: Roque")
print("Last Name: Dupra")
print("course: B.S.I.T")
print("Year: 3rd Year")
print("Age: 21")
print("Gender: Male")
print("Civil Status: Single")
print("Nationality: Filipino")
print("\n")
print("Motto: Roses are red, I'm going to bed")
print("school: PHINMA Aurollo University")
print("College: CITE")
print("==========================================")